######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 24 00:21:00 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += json.hpp
SOURCES += main.cpp
